# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-02 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_data', models.TextField(blank=True, editable=False)),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search', to='cms.Title')),
            ],
        ),
    ]
