# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('js_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_search', models.BooleanField(default=True, verbose_name='Show on search')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='js_search.SearchExtension')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
