# Generated by Django 3.2.19 on 2023-10-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_search', '0003_searchfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchfield',
            name='search_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Search target URL'),
        ),
    ]
